from typing import List, Optional
from typing_extensions import Literal

from ..._models import BaseModel
from ..completion_usage import CompletionUsage
from .chat_completion_message import ChatCompletionMessage
from .chat_completion_token_logprob import ChatCompletionTokenLogprob

__all__ = ["ChatCompletion", "Choice", "ChoiceLogprobs"]


class ChoiceLogprobs(BaseModel):
    """Log probability information for the choice."""

    content: Optional[List[ChatCompletionTokenLogprob]] = None
    """A list of message content tokens with log probability information."""
    refusal: Optional[List[ChatCompletionTokenLogprob]] = None
    """A list of message refusal tokens with log probability information."""


class Choice(BaseModel):
    finish_reason: Literal[
        "stop", "length", "tool_calls", "content_filter", "function_call"
    ]
    """The reason the model stopped generating tokens."""
    index: int
    """The index of the choice in the list of choices."""
    logprobs: Optional[ChoiceLogprobs] = None
    """Log probability information for the choice."""
    message: ChatCompletionMessage
    """A chat completion message generated by the model."""


class ChatCompletion(BaseModel):
    """Represents a chat completion response returned by model."""

    id: str
    """A unique identifier for the chat completion."""
    choices: List[Choice]
    """A list of chat completion choices."""
    created: int
    """The Unix timestamp (in seconds) of when the chat completion was created."""
    model: str
    """The model used for the chat completion."""
    object: Literal["chat.completion"]
    """The object type, which is always `chat.completion`."""
    service_tier: Optional[Literal["auto", "default", "flex", "scale", "priority"]] = (
        None
    )
    """Specifies the processing type used for serving the request."""
    system_fingerprint: Optional[str] = None
    """This fingerprint represents the backend configuration."""
    usage: Optional[CompletionUsage] = None
    """Usage statistics for the completion request."""
