# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.


from typing import Literal, TypeAlias

from ..._models import BaseModel
from ..shared.metadata import Metadata
from ..shared.reasoning import Reasoning
from ..shared.responses_model import ResponsesModel
from .response_error import ResponseError
from .response_input_item import ResponseInputItem
from .response_output_item import ResponseOutputItem
from .response_prompt import ResponsePrompt
from .response_status import ResponseStatus
from .response_text_config import ResponseTextConfig
from .response_usage import ResponseUsage
from .tool import Tool
from .tool_choice_allowed import ToolChoiceAllowed
from .tool_choice_apply_patch import ToolChoiceApplyPatch
from .tool_choice_custom import ToolChoiceCustom
from .tool_choice_function import ToolChoiceFunction
from .tool_choice_mcp import ToolChoiceMcp
from .tool_choice_options import ToolChoiceOptions
from .tool_choice_shell import ToolChoiceShell
from .tool_choice_types import ToolChoiceTypes

__all__ = ["Response", "IncompleteDetails", "ToolChoice", "Conversation"]


class IncompleteDetails(BaseModel):
    """Details about why the response is incomplete."""

    reason: Literal["max_output_tokens", "content_filter"] | None = None
    """The reason why the response is incomplete."""


ToolChoice: TypeAlias = (
    ToolChoiceOptions
    | ToolChoiceAllowed
    | ToolChoiceTypes
    | ToolChoiceFunction
    | ToolChoiceMcp
    | ToolChoiceCustom
    | ToolChoiceApplyPatch
    | ToolChoiceShell
)


class Conversation(BaseModel):
    """The conversation that this response belonged to."""

    id: str
    """The unique ID of the conversation that this response was associated with."""


class Response(BaseModel):
    id: str
    """Unique identifier for this Response."""
    created_at: float
    """Unix timestamp (in seconds) of when this Response was created."""
    error: ResponseError | None = None
    """An error object returned when the model fails to generate a Response."""
    incomplete_details: IncompleteDetails | None = None
    """Details about why the response is incomplete."""
    instructions: str | list[ResponseInputItem] | None = None
    """A system (or developer) message inserted into the model's context."""
    metadata: Metadata | None = None
    """Set of 16 key-value pairs that can be attached to an object."""
    model: ResponsesModel
    """Model ID used to generate the response, like `gpt-4o` or `o3`."""
    object: Literal["response"]
    """The object type of this resource - always set to `response`."""
    output: list[ResponseOutputItem]
    """An array of content items generated by the model."""
    parallel_tool_calls: bool
    """Whether to allow the model to run tool calls in parallel."""
    temperature: float | None = None
    """What sampling temperature to use, between 0 and 2."""
    tool_choice: ToolChoice
    """How the model should select which tool (or tools) to use."""
    tools: list[Tool]
    """An array of tools the model may call while generating a response."""
    top_p: float | None = None
    """An alternative to sampling with temperature."""
    background: bool | None = None
    """Whether to run the model response in the background."""
    completed_at: float | None = None
    """Unix timestamp (in seconds) of when this Response was completed."""
    conversation: Conversation | None = None
    """The conversation that this response belonged to."""
    max_output_tokens: int | None = None
    """An upper bound for the number of tokens that can be generated."""
    max_tool_calls: int | None = None
    """The maximum number of total calls to built-in tools."""
    previous_response_id: str | None = None
    """The unique ID of the previous response to the model."""
    prompt: ResponsePrompt | None = None
    """Reference to a prompt template and its variables."""
    prompt_cache_key: str | None = None
    """Used by OpenAI to cache responses for similar requests."""
    prompt_cache_retention: Literal["in_memory", "24h"] | None = None
    """The retention policy for the prompt cache."""
    reasoning: Reasoning | None = None
    """**gpt-5 and o-series models only** Configuration options for reasoning models."""
    safety_identifier: str | None = None
    """A stable identifier used to help detect users violating policies."""
    service_tier: Literal["auto", "default", "flex", "scale", "priority"] | None = None
    """Specifies the processing type used for serving the request."""
    status: ResponseStatus | None = None
    """The status of the response generation."""
    text: ResponseTextConfig | None = None
    """Configuration options for a text response from the model."""
    top_logprobs: int | None = None
    """Number of most likely tokens to return at each position."""
    truncation: Literal["auto", "disabled"] | None = None
    """The truncation strategy to use for the model response."""
    usage: ResponseUsage | None = None
    """Token usage details."""
    user: str | None = None
    """This field is being replaced by `safety_identifier` and `prompt_cache_key`."""

    @property
    def output_text(self) -> str:
        """Convenience property that aggregates all `output_text` items from the `output` list."""
        texts: list[str] = []
        for output in self.output:
            if output.type == "message":
                for content in output.content:
                    if content.type == "output_text":
                        texts.append(content.text)
        return "".join(texts)
