# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Union, Optional
from typing_extensions import Literal, TypeAlias

from .tool import Tool
from ..._models import BaseModel
from .response_error import ResponseError
from .response_usage import ResponseUsage
from .response_prompt import ResponsePrompt
from .response_status import ResponseStatus
from .tool_choice_mcp import ToolChoiceMcp
from ..shared.metadata import Metadata
from ..shared.reasoning import Reasoning
from .tool_choice_shell import ToolChoiceShell
from .tool_choice_types import ToolChoiceTypes
from .tool_choice_custom import ToolChoiceCustom
from .response_input_item import ResponseInputItem
from .tool_choice_allowed import ToolChoiceAllowed
from .tool_choice_options import ToolChoiceOptions
from .response_output_item import ResponseOutputItem
from .response_text_config import ResponseTextConfig
from .tool_choice_function import ToolChoiceFunction
from ..shared.responses_model import ResponsesModel
from .tool_choice_apply_patch import ToolChoiceApplyPatch

__all__ = ["Response", "IncompleteDetails", "ToolChoice", "Conversation"]


class IncompleteDetails(BaseModel):
    """Details about why the response is incomplete."""
    reason: Optional[Literal["max_output_tokens", "content_filter"]] = None
    """The reason why the response is incomplete."""


ToolChoice: TypeAlias = Union[
    ToolChoiceOptions,
    ToolChoiceAllowed,
    ToolChoiceTypes,
    ToolChoiceFunction,
    ToolChoiceMcp,
    ToolChoiceCustom,
    ToolChoiceApplyPatch,
    ToolChoiceShell,
]


class Conversation(BaseModel):
    """The conversation that this response belonged to."""
    id: str
    """The unique ID of the conversation that this response was associated with."""


class Response(BaseModel):
    id: str
    """Unique identifier for this Response."""
    created_at: float
    """Unix timestamp (in seconds) of when this Response was created."""
    error: Optional[ResponseError] = None
    """An error object returned when the model fails to generate a Response."""
    incomplete_details: Optional[IncompleteDetails] = None
    """Details about why the response is incomplete."""
    instructions: Union[str, List[ResponseInputItem], None] = None
    """A system (or developer) message inserted into the model's context."""
    metadata: Optional[Metadata] = None
    """Set of 16 key-value pairs that can be attached to an object."""
    model: ResponsesModel
    """Model ID used to generate the response, like `gpt-4o` or `o3`."""
    object: Literal["response"]
    """The object type of this resource - always set to `response`."""
    output: List[ResponseOutputItem]
    """An array of content items generated by the model."""
    parallel_tool_calls: bool
    """Whether to allow the model to run tool calls in parallel."""
    temperature: Optional[float] = None
    """What sampling temperature to use, between 0 and 2."""
    tool_choice: ToolChoice
    """How the model should select which tool (or tools) to use."""
    tools: List[Tool]
    """An array of tools the model may call while generating a response."""
    top_p: Optional[float] = None
    """An alternative to sampling with temperature."""
    background: Optional[bool] = None
    """Whether to run the model response in the background."""
    completed_at: Optional[float] = None
    """Unix timestamp (in seconds) of when this Response was completed."""
    conversation: Optional[Conversation] = None
    """The conversation that this response belonged to."""
    max_output_tokens: Optional[int] = None
    """An upper bound for the number of tokens that can be generated."""
    max_tool_calls: Optional[int] = None
    """The maximum number of total calls to built-in tools."""
    previous_response_id: Optional[str] = None
    """The unique ID of the previous response to the model."""
    prompt: Optional[ResponsePrompt] = None
    """Reference to a prompt template and its variables."""
    prompt_cache_key: Optional[str] = None
    """Used by OpenAI to cache responses for similar requests."""
    prompt_cache_retention: Optional[Literal["in_memory", "24h"]] = None
    """The retention policy for the prompt cache."""
    reasoning: Optional[Reasoning] = None
    """**gpt-5 and o-series models only** Configuration options for reasoning models."""
    safety_identifier: Optional[str] = None
    """A stable identifier used to help detect users violating policies."""
    service_tier: Optional[Literal["auto", "default", "flex", "scale", "priority"]] = None
    """Specifies the processing type used for serving the request."""
    status: Optional[ResponseStatus] = None
    """The status of the response generation."""
    text: Optional[ResponseTextConfig] = None
    """Configuration options for a text response from the model."""
    top_logprobs: Optional[int] = None
    """Number of most likely tokens to return at each position."""
    truncation: Optional[Literal["auto", "disabled"]] = None
    """The truncation strategy to use for the model response."""
    usage: Optional[ResponseUsage] = None
    """Token usage details."""
    user: Optional[str] = None
    """This field is being replaced by `safety_identifier` and `prompt_cache_key`."""

    @property
    def output_text(self) -> str:
        """Convenience property that aggregates all `output_text` items from the `output` list."""
        texts: List[str] = []
        for output in self.output:
            if output.type == "message":
                for content in output.content:
                    if content.type == "output_text":
                        texts.append(content.text)
        return "".join(texts)
