services:
  llm-plug:
    image: docker.cnb.cool/lfo.cc/llm-plug:latest
    container_name: llm-plug
    restart: unless-stopped
    ports:
      - "55555:55555"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
